# 测试环境
spring:
  # dubbo配置
  dubbo:
    jdUserService:
      version: 1.0.0-test
# 日志
logging:
  path: /data/project/nymph-dubbo/code



sharding:
  jdbc:
    datasource:
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mybatis_2
        username: root
        password:
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mybatis_3
        username: root
        password:
      names: ds0,ds1
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: shard
            algorithm-expression: ds$->{shard % 2}