# 公共配置
spring:
  # dubbo配置
  dubbo:
    address:
    application:
      name: nymph-dubbo

  # 数据库配置
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource

  # 打包配置文件
  profiles:
    active: "@activatedProperties@"

# memcached
#memcached:
#  allow-clear: true

# mybatis
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:config/logging-config.xml